name: Tests
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
    branches:
      - main
    tags: ["**"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
          cache: pip
      - name: Install Python dependencies
        run: |
          pip install ".[test]"
          pip list
      - name: Run tests
        run: |
          pytest
      # GitHub action reference: https://github.com/codecov/codecov-action
      - uses: codecov/codecov-action@v5
